apiVersion: v1
kind: Service
metadata:
  name: {{PLUGIN_SLUG}}
  namespace: nexus
  labels:
    app: {{PLUGIN_SLUG}}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{PLUGIN_SLUG}}
